CREATE TABLE public."Test" (id text NOT NULL);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public."Test" TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public."Test" TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public."Test" TO service_role;
